services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzPlatform\DraftsTools\Core\Repository\Repository:
        arguments:
            - "@ezpublish.api.persistence_handler"
            - "@ezpublish.spi.search"
            - '@ezpublish.search.background_indexer'
            - '@ezpublish.repository.relation_processor'
        lazy: true

    EzPlatform\DraftsTools\Core\Repository\DraftsToolsService:
        factory: ['@EzPlatform\DraftsTools\Core\Repository\Repository', 'getAllDraftsService']
        lazy: true

    #Deprecated. Use below DoctrineDatabase which use Doctrine\DBAL\Query\QueryBuilder
#    EzPlatform\DraftsTools\Core\Persistence\Gateway\DoctrineDatabaseLegacy:
#        arguments:
#            $dbHandler: '@ezpublish.api.storage_engine.legacy.dbhandler'

    EzPlatform\DraftsTools\Core\Persistence\Gateway\DoctrineDatabase: ~

    EzPlatform\DraftsTools\Core\Persistence\Gateway\ExceptionConversion:
        arguments:
            $innerGateway: '@EzPlatform\DraftsTools\Core\Persistence\Gateway\DoctrineDatabase'

    EzPlatform\DraftsTools\Core\Persistence\Handler:
        arguments:
            $draftsGateway: '@EzPlatform\DraftsTools\Core\Persistence\Gateway\ExceptionConversion'
            $contentGateway: '@ezpublish.persistence.legacy.content.gateway'

    #Dashboad Me-draft location(s) information
    EzPlatform\DraftsToolsBundle\Twig\DraftParentLocationExtension:
        tags:
            - { name: twig.extension }